'use client'

import "./globals.css";
import { useState } from 'react';
import { UserContext } from '../app/contexts/UserContext'
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });



export default function RootLayout({ children }) {
  const [currentUser, setCurrentUser] = useState(null);

  return (
    <UserContext.Provider value={{ currentUser, setCurrentUser }}>
    <head>
        <title>Virtuosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="business management" />
        
      </head>

      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>

    </UserContext.Provider>
  );
}
