'use client'

import "./globals.css";
import { useState } from 'react';
import { UserContext } from '../app/contexts/UserContext'
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Virtuosa",
//   description: "Generated by create next app",
//   keywords: "business management",
// };

export default function RootLayout({ children }) {
  const [currentUser, setCurrentUser] = useState(null);

  return (
    <UserContext.Provider value={{ currentUser, setCurrentUser }}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </UserContext.Provider>
  );
}
